version: "3.9"
services:
  web:
    build: .
    environment:
      db_user: postgres
      db_password: postgres
      db_name: uat_db
      db_host: localhost
      db_port: 5432
    ports:
      - "4455:80"
#    redis:
#      image: "redis:alpine"
